### ISSUE TITLE
Unable to connect to ros master

### ISSUE THREAD

**Issue by mrinalsenapati04** [ollide/rosjava_android_template#7]
Hi,
I am trying to connect to the ROS MASTER URI that i have generated by starting roscore.(http://mrinal-Nitro-AN515-42:11311/)
But it is showing that 'Unable to resolv host '.

**Comment by ollide** [comment]
Hi mrinalsenapati04,

have you been able to fix your problem?

The given URI looks like a local hostname that is probably not resolable on the Android device. Please make sure that both devices are on the same network and can communicate with each other.

I'll close this issue for now.
